import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MaintenanceApiService } from '../../core/api/maintenance-api.service';
import { PropertiesApiService } from '../../core/api/properties-api.service';
import { InventoryItem, Vendor, WorkOrder } from '../../shared/models/maintenance.models';
import { Property } from '../../shared/models/property.models';

import { BmStatusBadgeComponent } from '../../shared/components/bm-status-badge/bm-status-badge.component';

@Component({ selector: 'bm-maintenance', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink, BmStatusBadgeComponent], template: `
<div class="max-w-7xl mx-auto space-y-6">
  <div class="flex flex-wrap items-center justify-between gap-4"><div><div class="text-xs font-semibold uppercase tracking-wider text-emerald-700">Maintenance</div><h1 class="text-3xl font-bold text-slate-900 mt-1">{{ title() }}</h1><p class="text-sm text-slate-500 mt-1">Branch-scoped maintenance operations</p></div><button class="bm-btn bm-btn-primary" (click)="showForm.set(true)">Create {{ section() === 'work-orders' ? 'Work Order' : section() === 'vendors' ? 'Vendor' : 'Inventory Item' }}</button></div>
  <div class="flex gap-2 border-b border-slate-200"><a routerLink="/app/maintenance/work-orders" class="px-4 py-3 text-sm" [class.text-emerald-700]="section()==='work-orders'">Work Orders</a><a routerLink="/app/maintenance/vendors" class="px-4 py-3 text-sm" [class.text-emerald-700]="section()==='vendors'">Vendors</a><a routerLink="/app/maintenance/inventory" class="px-4 py-3 text-sm" [class.text-emerald-700]="section()==='inventory'">Inventory</a></div>
  @if (error()) { <div class="bm-card p-4 text-sm text-rose-700">{{ error() }}</div> }
  @if (section() === 'vendors') { <div class="bm-card overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Name</th><th class="p-4">Phone</th><th class="p-4">Email</th><th class="p-4">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@for (row of vendors(); track row.id) { <tr><td class="p-4 font-semibold">{{ row.name }}</td><td class="p-4">{{ row.phone || '—' }}</td><td class="p-4">{{ row.email || '—' }}</td><td class="p-4"><bm-status-badge [status]="row.status"></bm-status-badge></td></tr> } @empty { <tr><td colspan="4" class="p-8 text-center text-slate-500">No vendors found.</td></tr> }</tbody></table></div> }
  @if (section() === 'inventory') { <div class="bm-card overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">SKU</th><th class="p-4">Item</th><th class="p-4">Unit</th><th class="p-4">Stock</th><th class="p-4">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@for (row of inventory(); track row.id) { <tr><td class="p-4 font-semibold">{{ row.sku }}</td><td class="p-4">{{ row.name }}</td><td class="p-4">{{ row.unit_of_measure }}</td><td class="p-4 tabular-nums">{{ row.stock_on_hand }}</td><td class="p-4"><bm-status-badge [status]="row.status"></bm-status-badge></td></tr> } @empty { <tr><td colspan="5" class="p-8 text-center text-slate-500">No inventory items found.</td></tr> }</tbody></table></div> }
  @if (section() === 'work-orders') { <div class="bm-card overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Number</th><th class="p-4">Property</th><th class="p-4">Title</th><th class="p-4">Vendor</th><th class="p-4">Priority</th><th class="p-4">Status</th><th class="p-4">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@for (row of workOrders(); track row.id) { <tr><td class="p-4 font-semibold"><a [routerLink]="['/app/maintenance/work-orders', row.id]" class="text-emerald-700 hover:underline">{{ row.work_order_no }}</a></td><td class="p-4">{{ row.property?.name || row.property?.property_code || '—' }}</td><td class="p-4">{{ row.title }}</td><td class="p-4">{{ row.vendor?.name || '—' }}</td><td class="p-4"><bm-status-badge [status]="row.priority"></bm-status-badge></td><td class="p-4"><bm-status-badge [status]="row.status"></bm-status-badge></td><td class="p-4"><select class="bm-input text-xs" [value]="row.status" (change)="changeStatus(row.id, $any($event.target).value)"><option>open</option><option>assigned</option><option>in_progress</option><option>completed</option><option>cancelled</option></select></td></tr> } @empty { <tr><td colspan="7" class="p-8 text-center text-slate-500">No work orders found.</td></tr> }</tbody></table></div> }
  @if (showForm()) { <div class="fixed inset-0 z-50 bg-slate-900/40 flex items-center justify-center p-4"><div class="bm-card w-full max-w-2xl p-6 max-h-[90vh] overflow-y-auto"><div class="flex justify-between items-center mb-5"><h2 class="text-lg font-semibold">Create {{ title() }}</h2><button type="button" class="text-xl" (click)="showForm.set(false)">×</button></div>
    @if (section() === 'vendors') { <form [formGroup]="vendorForm" (ngSubmit)="saveVendor()" class="space-y-4"><input class="bm-input" placeholder="Vendor name" formControlName="name"><input class="bm-input" placeholder="Phone" formControlName="phone"><input class="bm-input" placeholder="Email" formControlName="email"><button class="bm-btn bm-btn-primary" [disabled]="vendorForm.invalid || saving()">Save Vendor</button></form> }
    @if (section() === 'inventory') { <form [formGroup]="inventoryForm" (ngSubmit)="saveInventory()" class="space-y-4"><input class="bm-input" placeholder="SKU" formControlName="sku"><input class="bm-input" placeholder="Item name" formControlName="name"><input class="bm-input" placeholder="Unit of measure" formControlName="unit_of_measure"><input class="bm-input" type="number" placeholder="Opening quantity" formControlName="opening_quantity"><button class="bm-btn bm-btn-primary" [disabled]="inventoryForm.invalid || saving()">Save Item</button></form> }
    @if (section() === 'work-orders') { <form [formGroup]="workOrderForm" (ngSubmit)="saveWorkOrder()" class="space-y-4"><select class="bm-input" formControlName="property_id"><option value="">Select property</option>@for (p of properties(); track p.id) { <option [value]="p.id">{{ p.property_code }} — {{ p.name }}</option> }</select><select class="bm-input" formControlName="vendor_id"><option value="">Select vendor</option>@for (v of vendors(); track v.id) { <option [value]="v.id">{{ v.name }}</option> }</select><input class="bm-input" placeholder="Title" formControlName="title"><textarea class="bm-input" rows="3" placeholder="Issue / request details" formControlName="description"></textarea><div class="grid grid-cols-2 gap-3"><select class="bm-input" formControlName="priority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input class="bm-input" type="number" min="0" step="0.01" placeholder="Service charge" formControlName="service_charge"></div><div formArrayName="lines" class="space-y-3"><div class="flex justify-between"><h3 class="font-semibold text-sm">Line items</h3><button type="button" class="text-emerald-700 text-sm" (click)="addLine()">+ Add line</button></div>@for (line of lines.controls; track $index) { <div [formGroupName]="$index" class="grid grid-cols-1 md:grid-cols-5 gap-2"><select class="bm-input" formControlName="line_type"><option value="service">Service</option><option value="inventory">Inventory</option></select><input class="bm-input md:col-span-2" placeholder="Particulars" formControlName="description"><select class="bm-input" formControlName="inventory_item_id"><option value="">Inventory item</option>@for (i of inventory(); track i.id) { <option [value]="i.id">{{ i.name }} ({{ i.stock_on_hand }})</option> }</select><input class="bm-input" type="number" min="0.01" step="0.01" placeholder="Qty" formControlName="quantity"><input class="bm-input" type="number" min="0" step="0.01" placeholder="Unit cost" formControlName="unit_cost"><button type="button" class="text-rose-600 text-xs" (click)="removeLine($index)">Remove</button></div>}</div><button class="bm-btn bm-btn-primary" [disabled]="workOrderForm.invalid || saving()">Create Work Order</button></form> }
  </div></div> }
</div>` })
export class MaintenanceComponent {
  private api=inject(MaintenanceApiService); private propertiesApi=inject(PropertiesApiService); private route=inject(ActivatedRoute); private fb=inject(FormBuilder);
  section=signal('work-orders'); title=signal('Work Orders'); showForm=signal(false); saving=signal(false); error=signal<string|null>(null); vendors=signal<Vendor[]>([]); inventory=signal<InventoryItem[]>([]); workOrders=signal<WorkOrder[]>([]); properties=signal<Property[]>([]);
  vendorForm=this.fb.nonNullable.group({name:['',Validators.required],phone:[''],email:['']}); inventoryForm=this.fb.nonNullable.group({sku:['',Validators.required],name:['',Validators.required],unit_of_measure:['piece',Validators.required],opening_quantity:[0,[Validators.required,Validators.min(0)]]});
  workOrderForm=this.fb.nonNullable.group({property_id:['',Validators.required],vendor_id:[''],title:['',Validators.required],description:[''],priority:['normal',Validators.required],service_charge:[0,[Validators.min(0)]],lines:this.fb.array([this.lineForm()])});
  constructor(){ this.route.data.subscribe(data=>{this.section.set(data['section']||'work-orders');this.title.set(data['title']||'Work Orders');this.load();}); }
  get lines(): FormArray { return this.workOrderForm.controls.lines; }
  lineForm(){return this.fb.nonNullable.group({line_type:['service',Validators.required],inventory_item_id:[''],description:['',Validators.required],quantity:[1,[Validators.required,Validators.min(0.01)]],unit_cost:[0,[Validators.required,Validators.min(0)]]});}
  addLine(){this.lines.push(this.lineForm());} removeLine(index:number){if(this.lines.length>1)this.lines.removeAt(index);}
  load(){this.error.set(null); if(this.section()==='vendors')this.api.vendors().subscribe({next:r=>this.vendors.set(r.data),error:e=>this.error.set(e.message)}); if(this.section()==='inventory')this.api.inventory().subscribe({next:r=>this.inventory.set(r.data),error:e=>this.error.set(e.message)}); if(this.section()==='work-orders'){this.api.workOrders().subscribe({next:r=>this.workOrders.set(r.data),error:e=>this.error.set(e.message)});this.api.vendors().subscribe({next:r=>this.vendors.set(r.data)});this.api.inventory().subscribe({next:r=>this.inventory.set(r.data)});this.propertiesApi.getProperties({per_page:100,status:'active'}).subscribe({next:r=>this.properties.set(r.data)});}}
  saveVendor(){if(this.vendorForm.invalid)return;this.saving.set(true);this.api.createVendor(this.vendorForm.getRawValue()).subscribe({next:()=>{this.saving.set(false);this.showForm.set(false);this.vendorForm.reset();this.load();},error:e=>{this.saving.set(false);this.error.set(e.message);}});}
  saveInventory(){if(this.inventoryForm.invalid)return;this.saving.set(true);this.api.createInventory(this.inventoryForm.getRawValue()).subscribe({next:()=>{this.saving.set(false);this.showForm.set(false);this.inventoryForm.reset({sku:'',name:'',unit_of_measure:'piece',opening_quantity:0});this.load();},error:e=>{this.saving.set(false);this.error.set(e.message);}});}
  saveWorkOrder(){if(this.workOrderForm.invalid)return;this.saving.set(true);const value=this.workOrderForm.getRawValue();this.api.createWorkOrder({...value,property_id:Number(value.property_id),vendor_id:value.vendor_id?Number(value.vendor_id):null,service_charge:Number(value.service_charge),lines:value.lines.map(line=>({...line,inventory_item_id:line.inventory_item_id?Number(line.inventory_item_id):null,quantity:Number(line.quantity),unit_cost:Number(line.unit_cost)}))}).subscribe({next:()=>{this.saving.set(false);this.showForm.set(false);this.load();},error:e=>{this.saving.set(false);this.error.set(e.message);}});}
  changeStatus(id:number,status:string){this.api.updateWorkOrderStatus(id,status).subscribe({next:()=>this.load(),error:e=>this.error.set(e.message)});}
}
