import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { MaintenanceApiService } from '../../core/api/maintenance-api.service';
import { InventoryItem, Vendor, WorkOrder, WorkOrderPayment } from '../../shared/models/maintenance.models';

import { BmStatusBadgeComponent } from '../../shared/components/bm-status-badge/bm-status-badge.component';

@Component({
  selector: 'bm-work-order-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, RouterLink, BmStatusBadgeComponent],
  template: `
    <div class="max-w-5xl mx-auto space-y-6">
      <div class="flex items-center justify-between gap-4"><div><a routerLink="/app/maintenance/work-orders" class="text-xs text-emerald-700">← Work Orders</a><h1 class="text-3xl font-bold text-slate-900 mt-2">{{ order()?.work_order_no || 'Work Order' }}</h1></div><div class="flex gap-2"><button type="button" class="bm-btn bm-btn-secondary" (click)="paymentOpen.set(true)">Add Payment</button><button type="button" class="bm-btn bm-btn-primary" (click)="editing.set(!editing())">{{ editing() ? 'Cancel' : 'Edit' }}</button></div></div>
      @if (error()) { <div class="bm-card p-4 text-sm text-rose-700">{{ error() }}</div> }
      @if (order(); as item) {
        @if (editing()) {
          <form [formGroup]="form" (ngSubmit)="save()" class="bm-card p-6 space-y-4"><input class="bm-input" formControlName="title" placeholder="Title"><textarea class="bm-input" rows="4" formControlName="description" placeholder="Description"></textarea><div class="grid grid-cols-1 md:grid-cols-3 gap-3"><select class="bm-input" formControlName="priority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><select class="bm-input" formControlName="vendor_id"><option value="">No vendor</option>@for (vendor of vendors(); track vendor.id) { <option [value]="vendor.id">{{ vendor.name }}</option> }</select><input class="bm-input" type="number" min="0" step="0.01" formControlName="service_charge" placeholder="Service charge"></div><select class="bm-input" formControlName="status"><option value="open">Open</option><option value="assigned">Assigned</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button class="bm-btn bm-btn-primary" [disabled]="form.invalid || saving()">Save Changes</button></form>
        } @else {
          <div class="bm-card p-6 grid grid-cols-1 md:grid-cols-2 gap-5 text-sm"><div><div class="text-slate-500">Property</div><div class="font-semibold mt-1">{{ item.property?.name || item.property?.property_code || '—' }}</div></div><div><div class="text-slate-500">Vendor</div><div class="font-semibold mt-1">{{ item.vendor?.name || '—' }}</div></div><div><div class="text-slate-500">Title</div><div class="font-semibold mt-1">{{ item.title }}</div></div><div><div class="text-slate-500">Status</div><div class="mt-1"><bm-status-badge [status]="item.status"></bm-status-badge></div></div><div><div class="text-slate-500">Priority</div><div class="mt-1"><bm-status-badge [status]="item.priority"></bm-status-badge></div></div><div><div class="text-slate-500">Service Charge</div><div class="font-semibold mt-1">AED {{ item.service_charge }}</div></div><div class="md:col-span-2"><div class="text-slate-500">Description</div><p class="mt-1 whitespace-pre-wrap">{{ item.description || '—' }}</p></div></div>
        }
        <div class="bm-card overflow-x-auto"><div class="p-5 border-b border-slate-100 font-semibold">Work Order Lines</div><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Type</th><th class="p-4">Particulars</th><th class="p-4">Inventory</th><th class="p-4">Qty</th><th class="p-4">Unit Cost</th><th class="p-4">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@for (line of item.lines || []; track line.id) { <tr><td class="p-4"><bm-status-badge [status]="line.line_type"></bm-status-badge></td><td class="p-4">{{ line.description }}</td><td class="p-4">{{ line.inventory_item?.name || '—' }}</td><td class="p-4">{{ line.quantity }}</td><td class="p-4">AED {{ line.unit_cost }}</td><td class="p-4 font-semibold">AED {{ (toNumber(line.quantity) * toNumber(line.unit_cost)).toFixed(2) }}</td></tr> } @empty { <tr><td colspan="6" class="p-6 text-center text-slate-500">No line items.</td></tr> }</tbody></table></div>
        <div class="bm-card overflow-x-auto"><div class="p-5 border-b border-slate-100 flex justify-between"><span class="font-semibold">Payments</span><span class="text-xs text-slate-500">Receipts and vouchers are generated when posted</span></div><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Direction</th><th class="p-4">Particulars</th><th class="p-4">Category</th><th class="p-4">Mode</th><th class="p-4">Amount</th><th class="p-4">Status</th><th class="p-4">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@for (payment of payments(); track payment.id) { <tr><td class="p-4"><bm-status-badge [status]="payment.direction"></bm-status-badge></td><td class="p-4">{{ payment.particulars }}</td><td class="p-4">{{ payment.category }}</td><td class="p-4"><bm-status-badge [status]="payment.payment_mode"></bm-status-badge></td><td class="p-4 font-semibold">AED {{ payment.amount }}</td><td class="p-4"><bm-status-badge [status]="payment.status"></bm-status-badge></td><td class="p-4"><button type="button" class="text-emerald-700 text-xs font-semibold" [disabled]="payment.status === 'paid'" (click)="setPaymentStatus(payment, 'paid')">Mark Paid</button></td></tr> } @empty { <tr><td colspan="7" class="p-6 text-center text-slate-500">No payments added.</td></tr> }</tbody></table></div>
      }
      @if (paymentOpen()) { <div class="fixed inset-0 z-50 bg-slate-900/40 flex items-center justify-center p-4"><form [formGroup]="paymentForm" (ngSubmit)="savePayment()" class="bm-card w-full max-w-xl p-6 space-y-4"><div class="flex justify-between"><h2 class="text-lg font-semibold">Add Work Order Payment</h2><button type="button" (click)="paymentOpen.set(false)">×</button></div><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><select class="bm-input" formControlName="direction"><option value="outward">Outward</option><option value="inward">Inward</option></select><input class="bm-input" formControlName="category" placeholder="Category"><input class="bm-input" formControlName="particulars" placeholder="Particulars"><input class="bm-input" type="number" min="0.01" step="0.01" formControlName="amount" placeholder="Amount"><input class="bm-input" type="date" formControlName="due_date"><select class="bm-input" formControlName="payment_mode"><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="bank_transfer">Bank Transfer</option></select><textarea class="bm-input md:col-span-2" formControlName="terms" rows="3" placeholder="Terms"></textarea></div><div class="flex justify-end gap-2"><button type="button" class="bm-btn bm-btn-secondary" (click)="paymentOpen.set(false)">Cancel</button><button class="bm-btn bm-btn-primary" [disabled]="paymentForm.invalid || saving()">Save Payment</button></div></form></div> }
    </div>
  `,
})
export class WorkOrderDetailComponent {
  private api = inject(MaintenanceApiService); private route = inject(ActivatedRoute); private fb = inject(FormBuilder);
  order = signal<WorkOrder | null>(null); payments = signal<WorkOrderPayment[]>([]); vendors = signal<Vendor[]>([]); inventory = signal<InventoryItem[]>([]); editing = signal(false); paymentOpen = signal(false); saving = signal(false); error = signal<string | null>(null);
  form = this.fb.nonNullable.group({ title: ['', Validators.required], description: [''], priority: ['normal', Validators.required], vendor_id: [''], service_charge: [0, [Validators.required, Validators.min(0)]], status: ['open', Validators.required] });
  paymentForm = this.fb.nonNullable.group({ direction: ['outward', Validators.required], category: ['', Validators.required], particulars: ['', Validators.required], amount: [0, [Validators.required, Validators.min(0.01)]], due_date: [new Date().toLocaleDateString('en-CA')], payment_mode: ['cash', Validators.required], terms: [''] });
  constructor() { this.load(); this.api.vendors().subscribe((response) => this.vendors.set(response.data)); }
  load(): void { const id = Number(this.route.snapshot.paramMap.get('id')); this.api.workOrder(id).subscribe({ next: (response) => { this.order.set(response.data); this.payments.set((response.data.payments || []) as WorkOrderPayment[]); this.form.patchValue({ title: response.data.title, description: response.data.description || '', priority: response.data.priority, vendor_id: response.data.vendor?.id ? String(response.data.vendor.id) : '', service_charge: Number(response.data.service_charge), status: response.data.status }); }, error: (error) => this.error.set(error.message || 'Unable to load work order.') }); }
  save(): void { const id = this.order()?.id; if (!id || this.form.invalid) return; this.saving.set(true); const value = this.form.getRawValue(); this.api.updateWorkOrder(id, { ...value, vendor_id: value.vendor_id ? Number(value.vendor_id) : null, service_charge: Number(value.service_charge) }).subscribe({ next: (response) => { this.order.set(response.data); this.editing.set(false); this.saving.set(false); }, error: (error) => { this.error.set(error.message || 'Unable to update work order.'); this.saving.set(false); } }); }
  toNumber(value: string | number): number { return Number(value) || 0; }
  savePayment(): void { const id = this.order()?.id; if (!id || this.paymentForm.invalid) return; this.saving.set(true); this.api.addWorkOrderPayment(id, this.paymentForm.getRawValue()).subscribe({ next: () => { this.paymentOpen.set(false); this.saving.set(false); this.load(); }, error: (error) => { this.error.set(error.message || 'Unable to add payment.'); this.saving.set(false); } }); }
  setPaymentStatus(payment: WorkOrderPayment, status: 'paid' | 'defaulted'): void { const id = this.order()?.id; if (!id) return; this.api.updateWorkOrderPaymentStatus(id, payment.id, status).subscribe({ next: () => this.load(), error: (error) => this.error.set(error.message || 'Unable to post payment.') }); }
}
